import React from 'react';

class UGDiscreteMathematics extends React.Component{

	render(){

		return(

			<div>

			    <h3>DISCRETE MATHEMATICS</h3>

			    <hr/>
			    <div className='wrapper'>
				    <h4>
				    OBJECTIVE
				    </h4>
				    <p>
					1. To learn main definitions, basic theorems and propositions 
					in Set theory and combinatorics and functions while designing algorithms.<br/>
					2. To achieve a firm command of the theory of Graphs, relations 
					and logic to solve a variety of problems under each proposed 
					scheme with algorithmic insight.<br/>
					3. To explore basic Graph theoretic and search methods by 
					application to important classical examples to Combinatorics, and algebraic systems.
					</p>
				</div>
				<hr/>

			    <div className='wrapper'>
				    <h4>
				    UNIT – I
				    </h4>
				    <p>
					<strong>Set Theory:</strong> Basic Set Operations - Cartesian Product and Power Sets. 
					<strong> Combinatorics:</strong> Basic Counting techniques - Permutations - 
					Partitions of Sets and Laws of addition - Combinations and Binomial theorem
					<strong> Logic:</strong> Propositions and logical operations - Truth tables and 
					propositions generated by a set - Equivalence and implication 
					- Laws of logic -Mathematical systems - Propositions over a 
					Universe - Mathematical induction - Quantifiers - Review of 
					methods of proof.
					<strong> More on sets:</strong> Minsets - Duality Principle.
					</p>
				</div>
				<hr/>
				
				<div className='wrapper'>
					<h4>
				    UNIT – II
				    </h4>
					<p>
					<strong>Relations and Graphs:</strong> Basic Definitions - Graphs of relations 
					- Properties of relations - Matrices 
					of relations - Closure operations on relations.
					<strong> Functions:</strong> Definition and notation-Injective, Surjective 
					and Bijective functions - Composition, Identity 
					and Inverses.
					<strong> Boolean Algebra:</strong> Lattices - Boolean Algebras 
					- Axioms of a Boolean Algebra - 
					Boolean identities - Karnaugh 
					Map method of simplifying Boolean 
					functions Quine-Mc-Clusky tabulation 
					method of simplifying Boolean functions - 
					Boolean expression - Application of Boolean 
					algebra to switching theory.
					</p>
				</div>
				<hr/>

				<div className='wrapper'>
					<h4>
				    UNIT - III
				    </h4>
					<p>
					<strong>Recursion and Recurrence Relations:</strong> Faces of recursion - Sequences - 
					Recurrence relations - Common 
					recurrence relations - Generating 
					functions - Recursion and Computer 
					Algebra Systems.
					<strong> Graph Theory:</strong> Introduction - Connectivity - 
					Transversals: Eulerian and 
					Hamiltonian - Graph Optimization - 
					Planarity and Colorings. Introduction to Trees.
					</p>
				</div>
				<hr/>

				<div className='wrapper'>
					<h4>
				    UNIT - IV
				    </h4>
					<p>
					<strong>Algebraic Systems:</strong> Operations - Algebraic Systems - Some general 
					properties of groups - Z<sub>n</sub> the integers modulo n - 
					Subsystems - Direct Products - Isomorphisms.
					<strong> Group Theory and Applications:</strong> Cyclic groups - Cosets and Factor groups - 
					Permutation groups - Normal Subgroups 
					and Group Homomorphisms - Coding 
					Theory - Group codes.
					<strong> Introduction to Rings and Fields:</strong> Rings - Basic definitions and 
					Concepts - Fields.
					</p>
				</div>
				<hr/>

				<div className='wrapper'>
					<h4>
				    TEXTBOOKS
				    </h4>
					<p>
					1. Alan Doerr and Kenneth Levasseur. Applied Discrete Structures 
					for Computer Science, 2nd Edition, Pearson Education: 2007. 
					(A Free electronic version under Creative Common Licence is 
					available for free download under the title 
					“Applied Discrete Structures”, Version 2, Year 2013)
					</p>
				</div>
				<hr/>

				<div className='wrapper'>
					<h4>
				    REFERENCES
				    </h4>
					<p>
					1. Kenneth H. Rosen. Discrete Mathematics and 
					its Applications, 7th Edition, McGraw Hill, 2012.<br/>
					2. Jean Paul Tremblay and Rampurkar Manohar. 
					Discrete Mathematical Structures With Applications 
					to Computer Science, McGraw Hill, 2005.<br/>
					3. Narsingh Deo. Graph Theory with Applications 
					to Engineering and Computer Science, Prentice Hall of India: 2004.
					</p>
				</div>
				<hr/>

			</div>
		)
	}
}

export default UGDiscreteMathematics;